spring:
  application:
    name: flyway-db-migration

  datasource:
    url: jdbc:postgresql://localhost:5432/job_scheduler
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true