spring:
  application:
    name: outbox-publisher

  datasource:
    url: jdbc:postgresql://localhost:5432/job_scheduler
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit


scheduler:
  publisher:
    lease-duration: 30s